=== sonyadk/web-course/sem3/xml/xml_3.dtd
<?xml version="1.0" ?>
<!ELEMENT statictics (MostView, StaticSystems, PhoneSystems, ips)>
<!ELEMENT MostView(#PCDATA)>

<!ELEMENT StaticSystems (Windows, Linux, MacOs)>
<!ELEMENT Windows(#PCDATA)>
<!ELEMENT Linux(#PCDATA)>
<!ELEMENT MacOs(#PCDATA)>

<!ELEMENT PhoneSystems(iPhone, Android, Other)>
<!ELEMENT iPhone(#PCDATA)>
<!ELEMENT Android(#PCDATA)>
<!ELEMENT Other(#PCDATA)>

<!ELEMENT ips(ip)+>
<!ELEMENT ip(#PCDATA)>

<!ATTLIST MostView adress CDATA #REQUIRED>

<!ATTLIST Windows view-count CDATA #REQUIRED>
<!ATTLIST Linux view-count CDATA #REQUIRED>
<!ATTLIST MacOs view-count CDATA #REQUIRED>

<!ATTLIST iPhone view-count CDATA #REQUIRED>
<!ATTLIST Android view-count CDATA #REQUIRED>
<!ATTLIST Other view-count CDATA #REQUIRED>

<!ATTLIST ip addr CDATA #REQUIRED>
<!ATTLIST ip frequenьеcy CDATA #REQUIRED>

=== sonyadk/web-course/sem3/xml/xml_3.xml
<?xml version="1.0" ?>
<!DOCTYPE statictics SYSTEM "xml_3.dtd">
<statictics>
  <MostView adress=""/>
  <StaticSystems>
	<Windows view-count=""/>
	<Linux view-count=""/>
	<MacOs view-count=""/>
  </StaticSystems>
  <PhoneSystems>
	<iPhone view-count=""/>
	<Android view-count=""/>
	<Other view-count=""/>
  </PhoneSystems>
  <ips> 
   <ip addr="" frequency=""/≻
   <ip addr="" frequency=""/≻
   <ip addr="" frequency=""/≻
   <ip addr="" frequency=""/≻
   <ip addr="" frequency=""/≻
  </ips>
</statictics>
